server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8
    username: root
    password: 1a2b3c4dZDQ
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#logging:
#  level:
#    root: info
#    file:
#      path: ./logs
